// Android Layout Editor for VS Code v2.9.0
const COMPONENT_DEFS={
LinearLayout:{group:'布局',icon:'▦',color:'var(--component-layout)',tag:'Layout',defaults:{orientation:'vertical',layout_width:'match_parent',layout_height:'wrap_content',background:'#ffffff',padding:'16dp',gravity:'start'},props:{orientation:{type:'select',options:['vertical','horizontal'],label:'方向'},gravity:{type:'select',options:['start','center','end','top','bottom'],label:'对齐'},background:{type:'color',label:'背景色'},padding:{type:'text',label:'内边距',unit:'dp'}},isContainer:true},
RelativeLayout:{group:'布局',icon:'⊞',color:'var(--component-layout)',tag:'Layout',defaults:{layout_width:'match_parent',layout_height:'wrap_content',background:'#ffffff',padding:'16dp'},props:{background:{type:'color',label:'背景色'},padding:{type:'text',label:'内边距',unit:'dp'}},isContainer:true},
ConstraintLayout:{group:'布局',icon:'⊞',color:'var(--component-layout)',tag:'Layout',defaults:{layout_width:'match_parent',layout_height:'match_parent',background:'#ffffff',padding:'16dp'},props:{background:{type:'color',label:'背景色'},padding:{type:'text',label:'内边距',unit:'dp'}},isContainer:true},
FrameLayout:{group:'布局',icon:'◻',color:'var(--component-layout)',tag:'Layout',defaults:{layout_width:'match_parent',layout_height:'wrap_content',background:'#ffffff',padding:'8dp'},props:{background:{type:'color',label:'背景色'},padding:{type:'text',label:'内边距',unit:'dp'}},isContainer:true},
ScrollView:{group:'布局',icon:'⇕',color:'var(--component-scroll)',tag:'Layout',defaults:{layout_width:'match_parent',layout_height:'match_parent',background:'#ffffff'},props:{background:{type:'color',label:'背景色'}},isContainer:true},
TextView:{group:'文本',icon:'T',color:'var(--component-text)',tag:'Widget',defaults:{text:'TextView',layout_width:'wrap_content',layout_height:'wrap_content',textSize:'14sp',textColor:'#333333',background:'transparent',padding:'8dp',layout_margin:'4dp',gravity:'start'},props:{text:{type:'text',label:'文本'},textSize:{type:'text',label:'字号',unit:'sp'},textColor:{type:'color',label:'文字颜色'},background:{type:'color',label:'背景色'},gravity:{type:'select',options:['start','center','end'],label:'对齐'}}},
Button:{group:'按钮',icon:'▢',color:'var(--component-button)',tag:'Widget',defaults:{text:'Button',layout_width:'wrap_content',layout_height:'wrap_content',textSize:'14sp',textColor:'#ffffff',background:'#4CAF50',padding:'10dp 24dp',layout_margin:'4dp'},props:{text:{type:'text',label:'文本'},textSize:{type:'text',label:'字号',unit:'sp'},textColor:{type:'color',label:'文字颜色'},background:{type:'color',label:'背景色'}}},
EditText:{group:'输入',icon:'▭',color:'var(--component-input)',tag:'Widget',defaults:{text:'',hint:'请输入内容',layout_width:'match_parent',layout_height:'wrap_content',textSize:'14sp',textColor:'#333333',background:'#f0f0f0',padding:'12dp',layout_margin:'4dp',inputType:'text'},props:{text:{type:'text',label:'文本'},hint:{type:'text',label:'提示'},textSize:{type:'text',label:'字号',unit:'sp'},inputType:{type:'select',options:['text','textPassword','number','phone','textEmailAddress'],label:'输入类型'}}},
ImageView:{group:'图片',icon:'🖼',color:'var(--component-image)',tag:'Widget',defaults:{layout_width:'100dp',layout_height:'100dp',background:'#e0e0e0',layout_margin:'4dp',scaleType:'centerCrop'},props:{layout_width:{type:'text',label:'宽度',unit:'dp'},layout_height:{type:'text',label:'高度',unit:'dp'},background:{type:'color',label:'背景色'},scaleType:{type:'select',options:['centerCrop','centerInside','fitCenter','fitXY'],label:'缩放'}}},
CheckBox:{group:'选择',icon:'☑',color:'var(--component-list)',tag:'Widget',defaults:{text:'CheckBox',layout_width:'wrap_content',layout_height:'wrap_content',textSize:'14sp',textColor:'#333333',layout_margin:'4dp'},props:{text:{type:'text',label:'文本'},textSize:{type:'text',label:'字号',unit:'sp'},checked:{type:'select',options:['false','true'],label:'选中'}}},
RadioButton:{group:'选择',icon:'◉',color:'var(--component-list)',tag:'Widget',defaults:{text:'RadioButton',layout_width:'wrap_content',layout_height:'wrap_content',textSize:'14sp',textColor:'#333333',layout_margin:'4dp'},props:{text:{type:'text',label:'文本'},textSize:{type:'text',label:'字号',unit:'sp'},checked:{type:'select',options:['false','true'],label:'选中'}}},
Switch:{group:'选择',icon:'⏻',color:'var(--component-list)',tag:'Widget',defaults:{text:'Switch',layout_width:'wrap_content',layout_height:'wrap_content',textSize:'14sp',textColor:'#333333',layout_margin:'4dp'},props:{text:{type:'text',label:'文本'},checked:{type:'select',options:['false','true'],label:'开启'}}},
ProgressBar:{group:'进度',icon:'▰',color:'var(--component-image)',tag:'Widget',defaults:{layout_width:'match_parent',layout_height:'wrap_content',layout_margin:'4dp'},props:{layout_width:{type:'text',label:'宽度',unit:'dp'}}}
};
let componentCounter=0,selectedId=null,components=[],undoStack=[],redoStack=[],currentZoom=1,isLandscape=false,vscode=null;
function init(){if(typeof acquireVsCodeApi!=='undefined'){vscode=acquireVsCodeApi();}renderComponentList();initEventListeners();if(window.INITIAL_XML){loadFromXML(window.INITIAL_XML);}else{addComponent('LinearLayout',null,true);}updateCanvasToolbarPosition();window.addEventListener('resize',updateCanvasToolbarPosition);}
function renderComponentList(){const list=document.getElementById('componentList');const groups={};Object.entries(COMPONENT_DEFS).forEach(([type,def])=>{if(!groups[def.group])groups[def.group]=[];groups[def.group].push({type,...def});});list.innerHTML=Object.entries(groups).map(([group,items])=>`<div class="component-group"><div class="component-group-title">${group}</div><div class="component-group-items">${items.map(item=>`<div class="component-item" draggable="true" data-type="${item.type}"><span class="icon" style="background:${item.color}20;color:${item.color}">${item.icon}</span><span class="label">${item.type}</span></div>`).join('')}</div></div>`).join('');document.querySelectorAll('.component-item').forEach(item=>{item.addEventListener('dragstart',handleDragStart);});}
function initEventListeners(){const phoneContent=document.getElementById('phoneContent');phoneContent.addEventListener('dragover',handleDragOver);phoneContent.addEventListener('drop',handleDrop);phoneContent.addEventListener('click',handleCanvasClick);document.getElementById('codeEditor').addEventListener('input',handleCodeInput);if(vscode){window.addEventListener('message',handleVSCodeMessage);}}
function handleVSCodeMessage(event){const message=event.data;switch(message.command){case'update':loadFromXML(message.xml);break;case'saved':showToast(message.success?'保存成功':'保存失败');break;case'fileContent':loadFromXML(message.xml);break;}}
function addComponent(type,parentId=null,isRoot=false){const def=COMPONENT_DEFS[type];const id=isRoot?'root':`comp_${++componentCounter}`;const component={id,type,parentId,props:{...def.defaults},children:[]};if(isRoot){components=[component];}else if(parentId){const parent=findComponent(parentId);if(parent)parent.children.push(component);}saveState();render();return id;}
function findComponent(id,list=components){for(const comp of list){if(comp.id===id)return comp;if(comp.children.length){const found=findComponent(id,comp.children);if(found)return found;}}return null;}
function render(){renderTree();renderCanvas();renderCode();updateStatusBar();}
function renderTree(){const tree=document.getElementById('componentTree');tree.innerHTML=renderTreeNode(components[0],0);}
function renderTreeNode(component,level){if(!component)return'';const def=COMPONENT_DEFS[component.type];const indent='  '.repeat(level);const hasChildren=component.children&&component.children.length;let html=`${indent}<div class="tree-node ${selectedId===component.id?'active':''}" data-id="${component.id}" onclick="selectComponent('${component.id}')"><span class="type-icon" style="color:${def.color}">${def.icon}</span>${component.type}</div>\n`;if(hasChildren){html+=component.children.map(child=>renderTreeNode(child,level+1)).join('');}return html;}
function renderCanvas(){const canvas=document.getElementById('phoneContent');if(components.length===0){canvas.innerHTML='';return;}canvas.innerHTML=renderComponentDOM(components[0]);document.querySelectorAll('.canvas-component').forEach(el=>{el.addEventListener('click',(e)=>{e.stopPropagation();selectComponent(el.dataset.id);});});}
function renderComponentDOM(component){const def=COMPONENT_DEFS[component.type];const isSelected=selectedId===component.id;const style=buildComponentStyle(component.props);let content='';if(component.children&&component.children.length){content=component.children.map(child=>renderComponentDOM(child)).join('');}else if(!def.isContainer){content=renderComponentContent(component);}return`<div class="canvas-component ${isSelected?'selected':''}" data-id="${component.id}" style="${style}">${isSelected?'<div class="component-label">'+component.type+'</div>':''}${content}</div>`;}
function buildComponentStyle(props){const style=[];if(props.layout_width)style.push(`width:${normalizeSize(props.layout_width)}`);if(props.layout_height)style.push(`height:${normalizeSize(props.layout_height)}`);if(props.background&&props.background!=='transparent')style.push(`background:${props.background}`);if(props.padding)style.push(`padding:${normalizeSize(props.padding)}`);if(props.layout_margin)style.push(`margin:${normalizeSize(props.layout_margin)}`);if(props.gravity)style.push(`text-align:${props.gravity}`);return style.join(';');}
function normalizeSize(size){if(size==='match_parent')return'100%';if(size==='wrap_content')return'auto';if(size.endsWith('dp'))return size.replace('dp','px');if(size.endsWith('sp'))return size.replace('sp','px');return size;}
function renderComponentContent(component){const props=component.props;switch(component.type){case'TextView':case'Button':case'CheckBox':case'RadioButton':case'Switch':return`<span style="color:${props.textColor||'#333'};font-size:${props.textSize||'14px'}">${props.text||''}</span>`;case'EditText':return`<input type="text" placeholder="${props.hint||''}" style="width:100%;padding:8px;border:1px solid #ccc;border-radius:4px" disabled>`;case'ImageView':return`<div style="width:100%;height:100%;background:${props.background||'#e0e0e0'};display:flex;align-items:center;justify-content:center">🖼</div>`;case'ProgressBar':return`<div style="width:100%;height:4px;background:#e0e0e0;border-radius:2px"><div style="width:60%;height:100%;background:var(--accent);border-radius:2px"></div></div>`;default:return'';}}
function renderCode(){const xml=generateXML();const editor=document.getElementById('codeEditor');const highlight=document.getElementById('codeHighlight');const lineNumbers=document.getElementById('lineNumbers');editor.value=xml;highlight.innerHTML=syntaxHighlight(xml);const lines=xml.split('\n').length;lineNumbers.innerHTML=Array.from({length:lines},(_,i)=>i+1).join('<br>');}
function syntaxHighlight(xml){return xml.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/(&lt;\/?)([\w:]+)/g,'$1<span class="tag">$2</span>').replace(/(\s)([\w:]+)=/g,'$1<span class="attr">$2</span>=').replace(/"([^"]*)"/g,'"<span class="value">$1</span>"');}
function generateXML(){if(components.length===0)return'';return'<?xml version="1.0" encoding="utf-8"?>\n'+generateComponentXML(components[0],0);}
function generateComponentXML(component,indent){const def=COMPONENT_DEFS[component.type];const spaces='    '.repeat(indent);const props=Object.entries(component.props).filter(([k,v])=>v&&v!=='false'&&!k.startsWith('layout_')).map(([k,v])=>`android:${k}="${v}"`).join('\n'+spaces+'    ');const layoutProps=Object.entries(component.props).filter(([k,v])=>k.startsWith('layout_')&&v).map(([k,v])=>`android:${k}="${v}"`).join('\n'+spaces+'    ');const allProps=[props,layoutProps].filter(Boolean).join('\n'+spaces+'    ');if(component.children&&component.children.length){const childrenXML=component.children.map(c=>generateComponentXML(c,indent+1)).join('\n');return`${spaces}<${component.type}\n${spaces}    ${allProps}>\n${childrenXML}\n${spaces}</${component.type}>`;}return`${spaces}<${component.type}\n${spaces}    ${allProps} />`;}
function selectComponent(id){selectedId=id;render();renderPropsPanel();}
function renderPropsPanel(){const empty=document.getElementById('propsEmpty');const content=document.getElementById('propsContent');if(!selectedId){empty.style.display='flex';content.style.display='none';return;}const component=findComponent(selectedId);if(!component)return;const def=COMPONENT_DEFS[component.type];empty.style.display='none';content.style.display='flex';content.innerHTML=Object.entries(def.props).map(([key,prop])=>{const value=component.props[key]||'';let input='';if(prop.type==='select'){input=`<select onchange="updateProp('${key}',this.value)">${prop.options.map(o=>`<option value="${o}"${o===value?' selected':''}>${o}</option>`).join('')}</select>`;}else if(prop.type==='color'){input=`<input type="color" value="${value||'#ffffff'}" onchange="updateProp('${key}',this.value)">`;}else{input=`<input type="text" value="${value}" onchange="updateProp('${key}',this.value)" placeholder="${prop.label}">`;}return`<div class="prop-row"><label>${prop.label}</label>${input}${prop.unit?`<span class="unit">${prop.unit}</span>`:''}</div>`;}).join('');}
function updateProp(key,value){if(!selectedId)return;const component=findComponent(selectedId);if(component){component.props[key]=value;saveState();render();}}
function deleteSelected(){if(!selectedId||selectedId==='root')return;deleteComponent(selectedId);selectedId=null;saveState();render();}
function deleteComponent(id){function removeFrom(list){const idx=list.findIndex(c=>c.id===id);if(idx>=0){list.splice(idx,1);return true;}for(const c of list){if(c.children&&removeFrom(c.children))return true;}return false;}removeFrom(components);}
function undo(){if(undoStack.length>1){redoStack.push(undoStack.pop());const state=undoStack[undoStack.length-1];components=JSON.parse(state);render();}}
function redo(){if(redoStack.length){const state=redoStack.pop();undoStack.push(state);components=JSON.parse(state);render();}}
function saveState(){undoStack.push(JSON.stringify(components));if(undoStack.length>50)undoStack.shift();redoStack=[];}
function clearAll(){if(confirm('确定要清空所有组件吗？')){components=[];componentCounter=0;selectedId=null;addComponent('LinearLayout',null,true);saveState();render();}}
function switchTab(tab){document.querySelectorAll('.center-tab').forEach(t=>t.classList.remove('active'));document.querySelector(`[data-tab="${tab}"]`).classList.add('active');const canvas=document.getElementById('canvasContainer');const code=document.getElementById('codeContainer');if(tab==='design'){canvas.style.display='block';code.style.display='none';}else if(tab==='code'){canvas.style.display='none';code.style.display='flex';}else{canvas.style.display='block';code.style.display='flex';canvas.style.flex='1';code.style.flex='1';}document.getElementById('statusView').textContent=tab==='design'?'设计视图':tab==='code'?'代码视图':'分屏视图';}
function togglePanel(side){document.getElementById(`panel${side==='left'?'Left':'Right'}`).classList.toggle('collapsed');}
function toggleSection(id){document.getElementById(id).classList.toggle('collapsed');}
function toggleOrientation(){isLandscape=!isLandscape;document.getElementById('phoneFrame').classList.toggle('landscape',isLandscape);}
function setPhoneRatio(ratio){const frame=document.getElementById('phoneFrame');if(ratio==='9-16'){frame.style.width='360px';frame.style.height='640px';}else if(ratio==='3-4'){frame.style.width='360px';frame.style.height='480px';}else if(ratio==='1-2'){frame.style.width='360px';frame.style.height='720px';}}
function setZoomFromInput(val){const zoom=parseInt(val)/100;if(zoom>=0.5&&zoom<=2){currentZoom=zoom;document.getElementById('phoneFrame').style.transform=`scale(${zoom})`;document.getElementById('statusZoom').textContent=`缩放:${val}`;}}
function fitToView(){currentZoom=1;document.getElementById('phoneFrame').style.transform='scale(1)';document.getElementById('zoomInput').value='100%';document.getElementById('statusZoom').textContent='缩放:100%';}
function toggleRuler(){document.getElementById('btnRuler').classList.toggle('active');}
function updateCanvasToolbarPosition(){const toolbar=document.getElementById('canvasToolbar');const container=document.getElementById('canvasContainer');if(toolbar&&container){const rect=container.getBoundingClientRect();toolbar.style.left=(rect.left+10)+'px';toolbar.style.top=(rect.top+10)+'px';}}
function handleDragStart(e){e.dataTransfer.setData('componentType',e.target.dataset.type);}
function handleDragOver(e){e.preventDefault();}
function handleDrop(e){e.preventDefault();const type=e.dataTransfer.getData('componentType');if(type){const targetId=e.target.closest('.canvas-component')?.dataset.id;if(targetId&&COMPONENT_DEFS[type]){addComponent(type,targetId);}}}
function handleCanvasClick(e){if(e.target.id==='phoneContent'){selectedId=null;render();}}
function handleCodeInput(e){clearTimeout(window.parseTimeout);window.parseTimeout=setTimeout(()=>{loadFromXML(e.target.value);},500);}
function loadFromXML(xml){try{const parser=new DOMParser();const doc=parser.parseFromString(xml,'text/xml');if(doc.documentElement.nodeName==='parsererror')return;components=[parseXMLNode(doc.documentElement,null)];render();}catch(e){console.error('Parse error:',e);}}
function parseXMLNode(node,parentId){const type=node.nodeName;const def=COMPONENT_DEFS[type]||COMPONENT_DEFS['LinearLayout'];const id=parentId?`comp_${++componentCounter}`:'root';const props={...def.defaults};for(const attr of node.attributes){if(attr.name.startsWith('android:')){props[attr.name.substring(8)]=attr.value;}}const component={id,type,parentId,props,children:[]};for(const child of node.children){component.children.push(parseXMLNode(child,id));}return component;}
function filterComponents(query){const items=document.querySelectorAll('.component-item');items.forEach(item=>{const type=item.dataset.type.toLowerCase();item.style.display=type.includes(query.toLowerCase())?'flex':'none';});}
function duplicateSelected(){if(!selectedId)return;const comp=findComponent(selectedId);if(comp&&comp.parentId){const newId=addComponent(comp.type,comp.parentId);const newComp=findComponent(newId);if(newComp){newComp.props={...comp.props};render();}}}
function moveUp(){showToast('上移功能');}
function moveDown(){showToast('下移功能');}
function ctxAction(action){if(action==='copy')duplicateSelected();else if(action==='up')moveUp();else if(action==='down')moveDown();else if(action==='delete')deleteSelected();document.getElementById('contextMenu').classList.remove('show');}
function openFile(){if(vscode){vscode.postMessage({command:'openFile'});}else{document.getElementById('fileInput').click();}}
function handleFileSelect(e){const file=e.target.files[0];if(file){const reader=new FileReader();reader.onload=(e)=>loadFromXML(e.target.result);reader.readAsText(file);}}
function saveToFile(){const xml=generateXML();if(vscode){vscode.postMessage({command:'save',xml});}else{const blob=new Blob([xml],{type:'text/xml'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='layout.xml';a.click();}}
function exportXML(){const xml=generateXML();if(vscode){vscode.postMessage({command:'export',xml});}else{saveToFile();}}
function showToast(message){const container=document.getElementById('toastContainer');const toast=document.createElement('div');toast.className='toast';toast.textContent=message;container.appendChild(toast);setTimeout(()=>toast.remove(),3000);}
function updateStatusBar(){const count=countComponents(components);document.getElementById('statusInfo').textContent=`组件:${count}`;document.getElementById('statusSelected').textContent=selectedId?findComponent(selectedId)?.type:'未选中';}
function countComponents(list){let count=list.length;for(const c of list){if(c.children)count+=countComponents(c.children);}return count;}
window.addEventListener('DOMContentLoaded',init);
